### ISSUE TITLE
Assertion error in fr text?

### ISSUE THREAD

**Issue by DougGore** [RaspberryPiFoundation/jam-photobooth#6]
I seem to be getting this error when running...

```python
Traceback (most recent call last):
  File "photobooth.py", line 3, in <module>
    from text import get_text
  File "/home/pi/jam-photobooth/text.py", line 84, in <module>
    assert all(ord(c) in range(128) for c in text), text
AssertionError: Tweeté!
```

Seems if I comment out the French strings, everything works. Is there some kind of parsing issue?

**Comment by DougGore** [comment]
Just a follow up, I think the issue is the accented e (é) is the cause as it's not in the lower ASCII range of 0 to 128 but instead 130 so the assertion is because it is out of range.

**Comment by bennuttall** [comment]
Thanks! The assertion error is to point out that there is an invalid character present. The picamera text overlay feature doesn't support characters out of the 128 range. Now fixed
